### PR TITLE
Improve dev linking with indexation

### PR DESCRIPTION
**Pull request by celian-garcia**
Before : 
```typescript
import {promLanguageDefinition} from 'monaco-promql/promql/promql.contribution';
```

After : 
```typescript
import {promLanguageDefinition} from 'monaco-promql';
```
> Both are still possible though

### CODE REVIEW

**Comment by celian-garcia** [comment]
Clarity is not the only benefit, we can now use ``npm link`` safely when developing

**Comment by Nexucis** [comment]
Actually, maybe a good way would be to provide a dev app inside the package.
Dev app that wouldn't be related to any typescript/javascript framework such as Angular or React.

That should be feasible by using directly webpack

**Comment by celian-garcia** [comment]
Currently I don't have any vanilla example like you mention, Angular and react examples are the dev app. Why not accept this PR and create an issue to create a vanilla devapp ?

Let me remind you that the dev linking is not the only benefit of this PR. Having a real index that export what we want to expose is improving the imports clarity.

**Comment by Nexucis** [comment]
I'm not against this PR quite far the opposite actually,

The vanilla way is just create a index.html file with a link to the typescript file (somehow) and then you have webpack that will build everything. That's how Angular is compiling/building. Angular just hide the complexity of Webpack

**Pull request merged**
